import { LANG, tOptional } from "../../i18n/runtime";

/**
 * M-03 copy. Existing Files/viewer keys stay in the F-07 dictionaries.
 * New search/filter/pagination/deep-link strings live here so we do not
 * rewrite the generated `i18n/en.ts` / `zh.ts` extract.
 */
const COPY: Record<"zh" | "en", Record<string, string>> = {
  zh: {
    "artifact.invalidMetadata": "响应未包含有效的产物元数据，导出已停止。",
    "editor.drafts": "保留的草稿（{0}）",
    "editor.draftIdentity": "会话 {0} · 基线 {1}",
    "editor.discard": "放弃这份草稿",
    "editor.noDrafts": "当前页面没有保留的草稿。",
    "editor.discardClose": "放弃草稿并关闭",
    "editor.discardCloseConfirm": "放弃这份草稿并关闭编辑器？未保存的修改将被删除。",
    "editor.keepClose": "保留草稿并关闭",
    "editor.copy": "复制草稿",
    "editor.viewLatest": "只读查看已核对版本",
    "editor.retryRead": "重试读取",
    "editor.discardReload": "放弃草稿并重新加载",
    "editor.discardConfirm": "放弃这份草稿并读取最新版本？未保存的修改将被删除。",
    "editor.memory": "草稿保留在当前页面内存中，切换标签或会话不会丢失；关闭或重新加载页面前请保存或复制。",
    "editor.problem.load": "无法读取固定版本原文。保存已禁用，可重试读取。",
    "editor.problem.capacity": "编辑器最多保留 10 份草稿，原文和修改合计 8 MiB。此文件保持只读；请先明确放弃其他草稿，或下载文件。",
    "editor.inputCapacity": "这次输入超出草稿总容量，未接受；之前的草稿已保留。请复制草稿或缩短输入。",
    "editor.problem.conflict": "文件版本已变化，保存被拒绝。草稿和原始基线已保留；请核对最新内容后明确放弃并重新加载。",
    "editor.problem.unknown": "无法确认保存结果，草稿已保留，未重发保存。以下读取仅核对版本事实。",
    "editor.problem.rejected": "保存被拒绝，草稿已保留。可复制草稿，或明确放弃后重新加载。",
    "editor.checking": "正在只读核对当前版本…",
    "editor.checkFailed": "版本核对失败；不能确认文件是否保存。",
    "editor.observedMatch": "读取到版本 {0}，内容与草稿相同。这不能确认是哪一次请求写入的。",
    "editor.observedDifferent": "读取到版本 {0}，内容与草稿不同。",
    "editor.copyManually": "自动复制失败，已选中草稿；请使用系统复制快捷键。",
    "viewer.text.truncated": "预览已截断。可展开已读取的完整原文，或下载文件。",
    "viewer.text.expand": "展开完整原文",
    "viewer.text.complete": "已展示完整原文。",
    "nb.artifact.saving": "正在保存输出…",
    "nb.artifact.unconfirmed": "历史版本无法确认",
    "nb.artifact.failed": "已确认版本读取失败",
    "nb.artifact.retry": "重试读取",
    "nb.artifact.latest": "打开最新版本",
    "nb.artifact.download": "下载此版本",
    "nb.artifact.open": "查看此版本",
    "files.search.ph": "按文件名搜索",
    "files.filter.type": "类型",
    "files.filter.type.ph": "content type",
    "files.filter.origin": "来源",
    "files.filter.origin.all": "全部",
    "files.filter.origin.uploaded": "上传",
    "files.filter.origin.generated": "生成",
    "files.loadMore": "加载更多",
    "files.noMatches": "没有匹配的文件。请调整或清空筛选条件。",
    "files.deeplink.copy": "复制深链",
    "files.deeplink.copied": "已复制",
    "files.version.stale": "找不到 version {0}（当前 latest 为 {1}）。不会改用 latest。",
    "files.version.notFound": "找不到该 Artifact 或指定 version。",
    "files.index.unavailable": "无法加载文件索引。",
    "artifact.editPinned": "当前标签页显示的是固定版本；请打开最新版本后再编辑",
    "prov.env.noSnapshot": "此版本未记录生产时环境（上传文件，或早于环境捕获功能生成）；不会用守护进程的实时环境替代。",
  },
  en: {
    "artifact.invalidMetadata": "The response does not contain valid artifact metadata. Export stopped.",
    "editor.drafts": "Retained drafts ({0})",
    "editor.draftIdentity": "Session {0} · baseline {1}",
    "editor.discard": "Discard this draft",
    "editor.noDrafts": "No drafts are retained in this page.",
    "editor.discardClose": "Discard draft and close",
    "editor.discardCloseConfirm": "Discard this draft and close the editor? Unsaved changes will be deleted.",
    "editor.keepClose": "Keep draft and close",
    "editor.copy": "Copy draft",
    "editor.viewLatest": "View checked version",
    "editor.retryRead": "Retry reading",
    "editor.discardReload": "Discard draft and reload",
    "editor.discardConfirm": "Discard this draft and read the latest version? Unsaved changes will be deleted.",
    "editor.memory": "Drafts stay in this page while switching tabs or sessions. Save or copy before closing or reloading the page.",
    "editor.problem.load": "Could not read the fixed original version. Saving is disabled; retry reading.",
    "editor.problem.capacity": "The editor holds up to 10 drafts and 8 MiB of original and edited text combined. This file stays read-only; explicitly discard other drafts or download it.",
    "editor.inputCapacity": "This input exceeded draft capacity and was not accepted. The previous draft is retained. Copy it or shorten the input.",
    "editor.problem.conflict": "The file version changed and the save was rejected. Your draft and original baseline are retained; review the current content before discarding and reloading.",
    "editor.problem.unknown": "The save result is unknown. Your draft is retained and the save was not resent. Reads below only check version facts.",
    "editor.problem.rejected": "The save was rejected. Your draft is retained. Copy it, or explicitly discard and reload.",
    "editor.checking": "Checking the current version without writing…",
    "editor.checkFailed": "Version checking failed; whether the file was saved remains unconfirmed.",
    "editor.observedMatch": "Read version {0}; its content matches the draft. This does not identify which request wrote it.",
    "editor.observedDifferent": "Read version {0}; its content differs from the draft.",
    "editor.copyManually": "Automatic copying failed. The draft is selected; use your system copy shortcut.",
    "viewer.text.truncated": "Preview truncated. Expand the complete text already loaded, or download the file.",
    "viewer.text.expand": "Show complete text",
    "viewer.text.complete": "Showing complete text.",
    "nb.artifact.saving": "Saving output…",
    "nb.artifact.unconfirmed": "Historical version could not be confirmed",
    "nb.artifact.failed": "Could not read the confirmed version",
    "nb.artifact.retry": "Retry reading",
    "nb.artifact.latest": "Open latest version",
    "nb.artifact.download": "Download this version",
    "nb.artifact.open": "Open this version",
    "files.search.ph": "Search by filename",
    "files.filter.type": "Type",
    "files.filter.type.ph": "content type",
    "files.filter.origin": "Source",
    "files.filter.origin.all": "All",
    "files.filter.origin.uploaded": "Uploaded",
    "files.filter.origin.generated": "Generated",
    "files.loadMore": "Load more",
    "files.noMatches": "No files match. Adjust or clear the filters.",
    "files.deeplink.copy": "Copy deep link",
    "files.deeplink.copied": "Copied",
    "files.version.stale": "Version {0} was not found (latest is {1}). Latest was not substituted.",
    "files.version.notFound": "This artifact or version was not found.",
    "files.index.unavailable": "Could not load the file index.",
    "artifact.editPinned": "This tab shows a fixed version; open the latest version to edit the file",
    "prov.env.noSnapshot": "No environment was recorded for this version (uploaded file, or produced before environment capture existed); the live daemon environment is not substituted.",
  },
};

export function filesT(key: string, ...args: unknown[]): string {
  const fromDict = tOptional(key);
  let s = fromDict != null ? fromDict : COPY[LANG]?.[key] || COPY.en[key] || key;
  if (args.length) {
    s = String(s).replace(/\{(\d+)\}/g, (m, i) =>
      args[+i] != null ? String(args[+i]) : m,
    );
  }
  return s;
}
