import { copyLookup, type CopyTable } from "../../i18n/copy";

const COPY: CopyTable = {
  en: {
    tab: "Lab", simulation: "Simulation · {0}", title: "Simulation bench",
    noSession: "Open a session to use Lab.", loading: "Reading confirmed state…",
    refresh: "Refresh", device: "Device", profile: "Profile", seed: "Seed (optional)",
    create: "Create experiment", unavailable: "Not modeled / unavailable", unknown: "Unknown",
    availabilityUnknown: "Device availability is unknown.", noDevices: "No simulation devices available.",
    run: "Run", noRuns: "No experiments in this session.", revision: "Revision {0}",
    steps: "Steps {0} / {1}", modelTime: "Model time, not seconds: {0}", latest: "Latest data: {0}",
    connected: "Connected", disconnected: "Disconnected · last confirmed state",
    vessels: "Sensor view", composition: "Composition unknown", layers: "Layer sensor intensity; colors do not identify materials.",
    observations: "Observations", source: "Source", unit: "Unit", quality: "Quality", operation: "Operation",
    execute: "Run one step", end: "End experiment", actions: "Actions", request: "Request",
    receipt: "Receipt", observation: "Observation", observationSequence: "Observation sequence {0}",
    unknownOutcome: "Outcome unknown. Query this command before taking another step.",
    reconcile: "Query result", retry: "Retry same request", pending: "Request in progress…",
    retryNotice: "No confirmed result. The original request and idempotency key are retained.",
    results: "Results", exportLater: "Result export will be available in a later update.",
    error: "Lab could not refresh: {0}", apiUnavailable: "Lab transport is unavailable.", apiTimeout: "Lab request timed out.",
    invalidSeed: "Seed must be an integer from 0 to 4294967295.",
    expectedRevision: "expected_revision {0}", parameter: "{0} {1} {2}",
    noReceipt: "No receipt", noObservation: "No observation", applied: "Applied: {0}",
    stopped: "Experiment ended", endedReason: "End reason: {0}",
    selectedAction: "Selected action", recentActions: "Latest {0} commands", state: "State: {0}",
  },
  zh: {
    tab: "Lab", simulation: "仿真 · {0}", title: "仿真实验台",
    noSession: "打开会话后使用 Lab。", loading: "正在读取已确认状态…",
    refresh: "刷新", device: "设备", profile: "Profile", seed: "Seed（可选）",
    create: "创建实验", unavailable: "未建模/不可用", unknown: "未知",
    availabilityUnknown: "设备可用性未知。", noDevices: "没有可用的仿真设备。",
    run: "实验", noRuns: "当前会话尚无实验。", revision: "Revision {0}",
    steps: "步数 {0} / {1}", modelTime: "模型时间，非秒：{0}", latest: "最近数据时间：{0}",
    connected: "已连接", disconnected: "连接断开 · 最近确认状态",
    vessels: "传感器视图", composition: "组成未知", layers: "液层传感器强度；颜色不代表材料种类。",
    observations: "观测", source: "来源", unit: "单位", quality: "质量", operation: "操作",
    execute: "执行单步", end: "结束实验", actions: "动作记录", request: "请求",
    receipt: "回执", observation: "观测", observationSequence: "观测序号 {0}",
    unknownOutcome: "结果未知。请先查询这条命令的结果，再执行下一步。",
    reconcile: "查询结果", retry: "重试原请求", pending: "请求正在处理…",
    retryNotice: "尚无确认结果。已保留原请求及幂等键。",
    results: "结果", exportLater: "结果导出将在后续更新中提供。",
    error: "Lab 刷新失败：{0}", apiUnavailable: "Lab 连接不可用。", apiTimeout: "Lab 请求超时。",
    invalidSeed: "Seed 必须为 0 到 4294967295 之间的整数。",
    expectedRevision: "expected_revision {0}", parameter: "{0} {1} {2}",
    noReceipt: "尚无回执", noObservation: "尚无观测", applied: "已应用：{0}",
    stopped: "实验已结束", endedReason: "结束原因：{0}",
    selectedAction: "已选动作", recentActions: "最近 {0} 条命令", state: "状态：{0}",
  },
};
export const labT = copyLookup(COPY);
