import { copyLookup, type CopyTable } from "../../i18n/copy";

/**
 * Auto Mode status and audit copy. Feature-local, so the generated
 * `i18n/en.ts` / `zh.ts` extract is not rewritten (docs/auto-mode.md §3 is
 * the source of every string the specification fixes).
 *
 * None of these values reads "On", "Enabled" or "已开启": a saved selection
 * is configuration, never a claim that anything is running.
 */
const COPY: CopyTable = {
  en: {
    "autoMode.block": "Auto Mode status",
    "autoMode.h.availability": "Availability",
    "autoMode.h.selection": "Saved selection",
    "autoMode.h.run": "Run",

    "autoMode.availability.stage2_feature_disabled": "Storage off",
    "autoMode.availability.import_quarantine": "Imported session, read only",
    "autoMode.availability.available": "Storage available",
    "autoMode.unavailable": "Status unavailable",
    "autoMode.notFound": "Session not found",
    "autoMode.loading": "Loading…",
    "autoMode.retry": "Retry reading",
    "autoMode.details": "Details",

    "autoMode.preset.off": "Off",
    "autoMode.preset.autonomous": "Autonomous",
    "autoMode.result.off": "Off",
    "autoMode.result.review_only": "Review only",
    "autoMode.result.auto_fix": "Auto-fix",
    "autoMode.approvals.user": "You",
    "autoMode.approvals.auto_review": "Auto review of asks",
    "autoMode.source.frame": "Saved on this conversation",
    "autoMode.source.project": "Saved on this project",
    "autoMode.source.deployment_explicit": "Set by deployment",
    "autoMode.source.legacy_result_review": "Inherited from Auto review",
    "autoMode.source.built_in_defaults": "Built-in default, no saved override",
    "autoMode.source.import_quarantine": "Held at the safe default after import",
    "autoMode.selection.line": "{0}; result review {1}; approvals {2}. {3}.",
    "autoMode.selection.deploymentFields": "Deployment sets: {0}.",
    "autoMode.field.preset": "preset",
    "autoMode.field.result_review_mode": "result review",
    "autoMode.field.approvals_reviewer": "approvals",
    "autoMode.list.join": ", ",

    "autoMode.run.none": "No Auto Run",
    "autoMode.run.inProgress": "In progress",
    "autoMode.run.finished": "Finished",
    "autoMode.run.lead": "{0}.",
    "autoMode.run.sentence": "{0}.",
    "autoMode.run.this": "This run: result review {0}; approvals {1}.",
    "autoMode.run.thisResult": "This run: result review {0}.",
    "autoMode.run.thisApprovals": "This run: approvals {0}.",
    "autoMode.run.rounds": "Review round {0} · repair round {1}.",
    "autoMode.run.reviewRound": "Review round {0}.",
    "autoMode.run.repairRound": "Repair round {0}.",
    "autoMode.run.id": "Run",
    "autoMode.run.turn": "Turn",
    "autoMode.run.execution": "Execution",

    "autoMode.status.running": "Running · not verified",
    "autoMode.status.candidate": "Candidate · provisional / not verified",
    "autoMode.status.reviewing": "Reviewing the candidate · not verified",
    "autoMode.status.repairing": "Repairing · not verified",
    "autoMode.status.verified": "Verified",
    "autoMode.status.completed_with_issues": "Completed · unverified · unresolved issues",
    "autoMode.status.review_unavailable": "Unavailable · not verified",
    "autoMode.status.blocked_by_guardian": "Blocked · Guardian",
    "autoMode.status.cancelled": "Cancelled",
    "autoMode.status.failed": "Failed",
    "autoMode.status.paused": "Paused",
    "autoMode.status.unverified_import": "Unverified · imported history",
    "autoMode.reason.policy_requires_explicit_setup": "Blocked · Policy requires explicit setup",
    "autoMode.reason.budget_exhausted": "Paused · Budget exhausted",
    "autoMode.reason.safe_rollback_unavailable": "Blocked · Safe rollback unavailable",
    "autoMode.reason.outcome_unknown": "Needs review · Outcome unknown",
    "autoMode.reason.loop_detected": "Paused/Blocked · Loop detected",
    "autoMode.reason.safety_boundary": "Failed · Safety boundary",
    "autoMode.reason.quota_exceeded": "Paused · Team quota exhausted",
    "autoMode.reason.budget_measurement_unavailable": "无法验证 token 预算",

    "autoMode.budget.title": "Deployment ceilings",
    "autoMode.budget.noUsage": "No usage recorded",
    "autoMode.budget.near": "Near ceiling",
    "autoMode.budget.at": "At ceiling",
    "autoMode.budget.tokenNotFrozen": "Token ceiling not frozen",
    "autoMode.budget.meter": "{0} of {1}, {2} remaining",
    "autoMode.budget.reserved": "{0} reserved",
    "autoMode.budget.nearCount": "{0} near ceiling",
    "autoMode.budget.atCount": "{0} at ceiling",
    "autoMode.budget.exhausted": "Exhausted: {0}.",
    "autoMode.budget.circuit": "Circuit tripped · {0}",
    "autoMode.budget.seconds": "{0} s",
    "autoMode.budget.multiplier": "{0}×",
    "autoMode.authority.auto_budget": "Auto Run",
    "autoMode.authority.guardian": "Guardian",
    "autoMode.ceiling.max_review_rounds": "Reviewer attempts per candidate",
    "autoMode.ceiling.max_repair_rounds": "Repair rounds",
    "autoMode.ceiling.repair_turns_per_round": "Repair turns per round",
    "autoMode.ceiling.max_extra_cells": "Additional Cells",
    "autoMode.ceiling.wall_time_s": "Auto Run wall time",
    "autoMode.ceiling.extra_token_multiplier": "Additional tokens over the initial turn",
    "autoMode.ceiling.repeated_finding_limit": "Repeated unchanged finding",
    "autoMode.ceiling.same_action_no_delta_limit": "Same action without a durable delta",
    "autoMode.ceiling.no_progress_turn_limit": "Turns without progress",
    "autoMode.ceiling.guardian_timeout_s": "Guardian decision timeout",
    "autoMode.ceiling.guardian_consecutive_denial_limit": "Consecutive Guardian denials",
    "autoMode.ceiling.guardian_window_size": "Guardian rolling window",
    "autoMode.ceiling.guardian_window_denial_limit": "Denials in that window",

    "autoMode.audit.open": "Audit",
    "autoMode.audit.title": "Audit",
    "autoMode.audit.filter": "Audit kind",
    "autoMode.audit.kind.all": "All kinds",
    "autoMode.audit.kind.result_review": "Result review",
    "autoMode.audit.kind.permission_review": "Permission review",
    "autoMode.audit.entity.candidate_evidence_snapshot": "Candidate evidence snapshot",
    "autoMode.audit.entity.approval_action": "Approval action",
    "autoMode.audit.empty": "No audits",
    "autoMode.audit.unavailable": "Audits unavailable",
    "autoMode.audit.more": "Load more",
    "autoMode.audit.summary": "Summary",
    "autoMode.audit.findings": "Findings",
    "autoMode.audit.fallback": "{0} · {1}",
    "autoMode.audit.f.subject_entity_kind": "Subject",
    "autoMode.audit.f.status": "Status",
    "autoMode.audit.f.verdict": "Verdict",
    "autoMode.audit.f.outcome": "Outcome",
    "autoMode.audit.f.decision": "Decision",
    "autoMode.audit.f.risk": "Risk",
    "autoMode.audit.f.round": "Round",
    "autoMode.audit.f.attempt": "Attempt",
    "autoMode.audit.f.finding_count": "Findings",
    "autoMode.audit.f.error_kind": "Error",
    "autoMode.audit.f.created_at": "Created",
    "autoMode.audit.f.started_at": "Started",
    "autoMode.audit.f.completed_at": "Completed",
    "autoMode.audit.f.event_ordinal": "Event",
    "autoMode.audit.f.audit_id": "Audit",
    "autoMode.audit.f.run_id": "Run",
    "autoMode.audit.f.reviewer_profile_id": "Reviewer profile",
    "autoMode.audit.f.profile_revision": "Profile revision",
    "autoMode.audit.f.severity": "Severity",
    "autoMode.audit.f.category": "Category",
    "autoMode.audit.f.evidence_refs": "Evidence",
    "autoMode.audit.f.version_ids": "Versions",
    "autoMode.audit.f.artifact_ids": "Artifacts",
    "autoMode.audit.f.cell_ids": "Cells",
    "autoMode.audit.f.finding_id": "Finding",
    "autoMode.audit.f.fingerprint": "Fingerprint",
  },
  zh: {
    "autoMode.block": "自动模式状态",
    "autoMode.h.availability": "可用性",
    "autoMode.h.selection": "已保存的选择",
    "autoMode.h.run": "运行",

    "autoMode.availability.stage2_feature_disabled": "存储未开启",
    "autoMode.availability.import_quarantine": "导入会话，只读",
    "autoMode.availability.available": "存储可用",
    "autoMode.unavailable": "状态不可用",
    "autoMode.notFound": "找不到会话",
    "autoMode.loading": "正在读取…",
    "autoMode.retry": "重试读取",
    "autoMode.details": "详情",

    "autoMode.preset.off": "关闭",
    "autoMode.preset.autonomous": "自主",
    "autoMode.result.off": "关闭",
    "autoMode.result.review_only": "仅审核",
    "autoMode.result.auto_fix": "自动修复",
    "autoMode.approvals.user": "由你",
    "autoMode.approvals.auto_review": "自动复核询问",
    "autoMode.source.frame": "已保存在此会话",
    "autoMode.source.project": "已保存在此项目",
    "autoMode.source.deployment_explicit": "由部署配置指定",
    "autoMode.source.legacy_result_review": "继承自自动审核",
    "autoMode.source.built_in_defaults": "内置默认，没有已保存的覆盖",
    "autoMode.source.import_quarantine": "导入后固定为安全默认",
    "autoMode.selection.line": "{0}；结果审核 {1}；审批 {2}。{3}。",
    "autoMode.selection.deploymentFields": "部署配置指定的字段：{0}。",
    "autoMode.field.preset": "预设",
    "autoMode.field.result_review_mode": "结果审核",
    "autoMode.field.approvals_reviewer": "审批",
    "autoMode.list.join": "、",

    "autoMode.run.none": "没有自动运行",
    "autoMode.run.inProgress": "进行中",
    "autoMode.run.finished": "已结束",
    "autoMode.run.lead": "{0}。",
    "autoMode.run.sentence": "{0}。",
    "autoMode.run.this": "本次运行：结果审核 {0}；审批 {1}。",
    "autoMode.run.thisResult": "本次运行：结果审核 {0}。",
    "autoMode.run.thisApprovals": "本次运行：审批 {0}。",
    "autoMode.run.rounds": "审核第 {0} 轮 · 修复第 {1} 轮。",
    "autoMode.run.reviewRound": "审核第 {0} 轮。",
    "autoMode.run.repairRound": "修复第 {0} 轮。",
    "autoMode.run.id": "运行",
    "autoMode.run.turn": "回合",
    "autoMode.run.execution": "执行",

    "autoMode.status.running": "运行中 · 未验证",
    "autoMode.status.candidate": "候选 · 临时 / 未验证",
    "autoMode.status.reviewing": "正在审核候选 · 未验证",
    "autoMode.status.repairing": "正在修复 · 未验证",
    "autoMode.status.verified": "已验证",
    "autoMode.status.completed_with_issues": "已完成 · 未验证 · 有未解决的问题",
    "autoMode.status.review_unavailable": "审核不可用 · 未验证",
    "autoMode.status.blocked_by_guardian": "已阻止 · 权限守护",
    "autoMode.status.cancelled": "已取消",
    "autoMode.status.failed": "失败",
    "autoMode.status.paused": "已暂停",
    "autoMode.status.unverified_import": "未验证 · 导入的历史",
    "autoMode.reason.policy_requires_explicit_setup": "已阻止 · 策略需要显式设置",
    "autoMode.reason.budget_exhausted": "已暂停 · 预算耗尽",
    "autoMode.reason.safe_rollback_unavailable": "已阻止 · 无法安全回滚",
    "autoMode.reason.outcome_unknown": "需要复核 · 结果未知",
    "autoMode.reason.loop_detected": "已暂停/已阻止 · 检测到循环",
    "autoMode.reason.safety_boundary": "失败 · 安全边界",
    "autoMode.reason.quota_exceeded": "已暂停 · 团队配额耗尽",
    "autoMode.reason.budget_measurement_unavailable": "无法验证 token 预算",

    "autoMode.budget.title": "部署上限",
    "autoMode.budget.noUsage": "尚未记录用量",
    "autoMode.budget.near": "接近上限",
    "autoMode.budget.at": "已到上限",
    "autoMode.budget.tokenNotFrozen": "令牌上限尚未冻结",
    "autoMode.budget.meter": "已用 {0}/{1}，剩余 {2}",
    "autoMode.budget.reserved": "预留 {0}",
    "autoMode.budget.nearCount": "{0} 项接近上限",
    "autoMode.budget.atCount": "{0} 项已到上限",
    "autoMode.budget.exhausted": "已耗尽：{0}。",
    "autoMode.budget.circuit": "熔断已触发 · {0}",
    "autoMode.budget.seconds": "{0} 秒",
    "autoMode.budget.multiplier": "{0}×",
    "autoMode.authority.auto_budget": "自动运行",
    "autoMode.authority.guardian": "权限守护",
    "autoMode.ceiling.max_review_rounds": "每个候选的审核尝试",
    "autoMode.ceiling.max_repair_rounds": "修复轮数",
    "autoMode.ceiling.repair_turns_per_round": "每轮修复回合",
    "autoMode.ceiling.max_extra_cells": "额外 Cell",
    "autoMode.ceiling.wall_time_s": "自动运行时长",
    "autoMode.ceiling.extra_token_multiplier": "超出初始回合的额外令牌",
    "autoMode.ceiling.repeated_finding_limit": "重复且未变化的发现",
    "autoMode.ceiling.same_action_no_delta_limit": "无持久变化的相同动作",
    "autoMode.ceiling.no_progress_turn_limit": "无进展回合",
    "autoMode.ceiling.guardian_timeout_s": "权限守护决策超时",
    "autoMode.ceiling.guardian_consecutive_denial_limit": "连续的权限守护拒绝",
    "autoMode.ceiling.guardian_window_size": "权限守护滚动窗口",
    "autoMode.ceiling.guardian_window_denial_limit": "窗口内的拒绝",

    "autoMode.audit.open": "审计",
    "autoMode.audit.title": "审计",
    "autoMode.audit.filter": "审计类型",
    "autoMode.audit.kind.all": "全部类型",
    "autoMode.audit.kind.result_review": "结果审核",
    "autoMode.audit.kind.permission_review": "权限审核",
    "autoMode.audit.entity.candidate_evidence_snapshot": "候选证据快照",
    "autoMode.audit.entity.approval_action": "审批动作",
    "autoMode.audit.empty": "没有审计记录",
    "autoMode.audit.unavailable": "审计不可用",
    "autoMode.audit.more": "加载更多",
    "autoMode.audit.summary": "摘要",
    "autoMode.audit.findings": "发现",
    "autoMode.audit.fallback": "{0} · {1}",
    "autoMode.audit.f.subject_entity_kind": "对象",
    "autoMode.audit.f.status": "状态",
    "autoMode.audit.f.verdict": "结论",
    "autoMode.audit.f.outcome": "结果",
    "autoMode.audit.f.decision": "决定",
    "autoMode.audit.f.risk": "风险",
    "autoMode.audit.f.round": "轮次",
    "autoMode.audit.f.attempt": "尝试",
    "autoMode.audit.f.finding_count": "发现数",
    "autoMode.audit.f.error_kind": "错误",
    "autoMode.audit.f.created_at": "创建于",
    "autoMode.audit.f.started_at": "开始于",
    "autoMode.audit.f.completed_at": "完成于",
    "autoMode.audit.f.event_ordinal": "事件",
    "autoMode.audit.f.audit_id": "审计",
    "autoMode.audit.f.run_id": "运行",
    "autoMode.audit.f.reviewer_profile_id": "审核者配置",
    "autoMode.audit.f.profile_revision": "配置修订",
    "autoMode.audit.f.severity": "严重程度",
    "autoMode.audit.f.category": "类别",
    "autoMode.audit.f.evidence_refs": "证据",
    "autoMode.audit.f.version_ids": "版本",
    "autoMode.audit.f.artifact_ids": "产物",
    "autoMode.audit.f.cell_ids": "Cell",
    "autoMode.audit.f.finding_id": "发现",
    "autoMode.audit.f.fingerprint": "指纹",
  },
};

export const autoModeT = copyLookup(COPY);

/** The keys of both languages, for the parity test. */
export function autoModeCopyKeys(): { en: string[]; zh: string[] } {
  return { en: Object.keys(COPY.en).sort(), zh: Object.keys(COPY.zh).sort() };
}
